/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    kotlin("jvm") version "1.5.10"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jcenter.bintray.com")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.postgresql:postgresql:42.2.5")
    implementation("com.google.code.gson:gson:2.8.5")
    implementation("org.jdbi:jdbi3-core:3.6.0")
    implementation("io.ktor:ktor-server-core:1.1.3")
    implementation("io.ktor:ktor-server-netty:1.1.3")
    implementation("io.ktor:ktor-jackson:1.1.3")
    implementation("io.ktor:ktor-freemarker:1.1.3")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.21")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.21")
    testImplementation("junit:junit:4.11")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.3.21")
}

group = "com.ultimaspin"
version = "1.0-SNAPSHOT"
description = "ply-api"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
