/*
 * This file was generated by the Gradle 'init' task.
 */

val kotlinVersion = "1.5.10"
val ktorVersion = "1.6.0"

plugins {
    java
    kotlin("jvm") version "1.5.10"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jcenter.bintray.com")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.postgresql:postgresql:42.2.5")
    implementation("com.google.code.gson:gson:2.8.5")
    implementation("org.jdbi:jdbi3-core:3.6.0")
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.ktor:ktor-jackson:$ktorVersion")
    implementation("io.ktor:ktor-freemarker:$ktorVersion")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
    testImplementation("junit:junit:4.11")
}

group = "com.ultimaspin"
version = "1.0-SNAPSHOT"
description = "ply-api"

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
