[package]
name = "hello-rust"
version = "0.1.0"
authors = ["William Do <william@ultimaspin.com>"]
edition = "2018"

[dependencies]
postgres = "0.15"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0"