version: "3.9"  # optional since v1.27.0
services:

  ply-retro:
    build: ./ply-retro
    ports:
      - "8888:8080"
    environment:
      CATALINA_OPTS: "-DdbConnectionUrl=jdbc:postgresql://db:5432/ply"
  db:
    build: ./ply/db
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: docker
