version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: docker
